version: "3.9"

services:
  web:
    container_name: web
    build: .
    restart: always
    ports:
      - "4000:4000"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SECRET=${SECRET}
      - NODE_ENV=production
    command: /bin/sh -c "npm install && npm run dev"
