version: "3.9"

services:
  web:
    container_name: node-web
    image: ${IMAGE}   # Image pushed to Nexus
    restart: always
    ports:
      - "4000:4000"
    environment:
      - DATABASE_HOST
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_NAME
      - DATABASE_PORT
      - SECRET
