version: "3.9"

services:
  web:
    container_name: web
    build: .
    restart: always
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    command: /bin/sh -c 'npm install && npm run dev'
