version: "3.9"

services:
  web:
    container_name: web
    image: 10.0.1.208:5000/my-nodejs-app:latest   # 👈 pull from Nexus on Jenkins server
    restart: always
    ports:
      - "4000:4000"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SECRET=${SECRET}
      - NODE_ENV=production
    command: /bin/sh -c "npm run dev"
