version: "3.9"

services:
  web:
    container_name: web
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/notesdb
      - PORT=4000
      - NODE_ENV=production
    command: npm run dev

  mongo:
    container_name: database
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - mongo-data:/data/db
 
volumes:
  mongo-data:
